version: '3.8'
services:
  db:
    image: postgres:14
    container_name: crypto-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto
    ports:
      - '5432:5432'

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
        - '6379:6379'
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db